import { cx } from "@/src/utils";
import "./globals.css";
import { Inter, Manrope } from "next/font/google";
import Header from "@/src/components/Header";
import Footer from "../components/Footer";
import ScrollToTopButton from "../components/Elements/ScrollToTop";
import StoreProvider from "../redux/provider";
import Script from "next/script";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-in",
});
const manrope = Manrope({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-man",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={cx(
          inter.variable,
          manrope.variable,
          "font-dosis bg-light dark:bg-black"
        )}
      >
        <Script id={1}>
          {`if (localStorage.getItem('theme') === 'dark' || (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
  document.documentElement.classList.add('dark')
} else {
  document.documentElement.classList.remove('dark')
}`}
        </Script>
        <StoreProvider>
          <Header />
          {children}
          <ScrollToTopButton />
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
